grafana:
  enabled: false
  ingress:
    enabled: false

loki:
  service:
    type: NodePort
    nodePort: 32002
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - loki.local
    paths:
      - /
    tls: []

promtail:
  enabled: true
