apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  sources:

    # 1 - Loki & Promtail
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki-stack
      targetRevision: 2.10.0
      helm:
        valueFiles:
          - $values/monitoring/loki-values.yaml

    # 2 - Values file source (this Git repo)
    - repoURL: 'https://github.com/maheshgowdamg/monitoring.git'
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

