apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  sources:

    # 1 - Prometheus & Grafana
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 65.4.0
      helm:
        valueFiles:
          - $values/monitoring/prometheus-values.yaml

    # 2 - Values file source (this Git repo)
    - repoURL: 'https://github.com/maheshgowdamg/monitoring.git'
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

